window.DEFAULT_NSFW_DICT = {
  "NSFW": {
    "expression": [
      { "tag": "aroused",          "ja": "上気した表情", "level": "L1" },
      { "tag": "flushed",          "ja": "頬を赤らめる", "level": "L1" },
      { "tag": "embarrassed",      "ja": "照れ", "level": "L1" },
      { "tag": "seductive_smile",  "ja": "誘惑の微笑み", "level": "L1" },
      { "tag": "half_lidded_eyes", "ja": "とろんとした目", "level": "L1" },
      { "tag": "bedroom_eyes",     "ja": "潤んだ目", "level": "L1" },
      { "tag": "lip_bite",         "ja": "唇を噛む", "level": "L1" },
      { "tag": "pouting",          "ja": "むくれ顔", "level": "L1" },
      { "tag": "bashful_smile",    "ja": "はにかみ笑顔", "level": "L1" },
      { "tag": "soft_moan",        "ja": "小さな喘ぎ声", "level": "L1" },
      { "tag": "smirk",            "ja": "ニヤリ顔（片笑い）",      "level": "L1" },
      { "tag": "sparkly_eyes",     "ja": "キラキラ目（ときめき）",  "level": "L1" },
      { "tag": "bashful_side_glance", "ja": "照れ横目",             "level": "L1" },
      { "tag": "teary_smile",      "ja": "涙ぐみ笑顔",              "level": "L2" },
      { "tag": "sadistic_smile",   "ja": "Sっ気の笑み",             "level": "L2" },
      { "tag": "masochistic_blush","ja": "Mっ気の上気顔",           "level": "L2" },
      { "tag": "ecstatic_tongue",  "ja": "舌出し恍惚顔",            "level": "L2" },
      { "tag": "dazed_smile",      "ja": "ぼんやり笑顔",            "level": "L1" },
      { "tag": "angry_blush",      "ja": "怒り＋赤面",              "level": "L1" },
      { "tag": "teasing_grin",     "ja": "からかい笑顔",            "level": "L1" },
      { "tag": "pleading_eyes",    "ja": "お願い目（うるうる）",    "level": "L1" },
      { "tag": "fearful_cry",      "ja": "怯え泣き顔",              "level": "L3" },
      { "tag": "resigned_face",    "ja": "諦め顔",                  "level": "L2" },
      { "tag": "overjoyed",        "ja": "歓喜の笑顔",              "level": "L1" },
      { "tag": "dizzy_face",       "ja": "ぐるぐる目（くらくら）",  "level": "L1" },
    
      { "tag": "tongue_out",       "ja": "舌を出す", "level": "L2" },
      { "tag": "panting",          "ja": "息を荒くする", "level": "L2" },
      { "tag": "moist_lips",       "ja": "艶のある唇", "level": "L2" },
      { "tag": "ecstasy",          "ja": "恍惚", "level": "L2" },
      { "tag": "tearful",          "ja": "涙目", "level": "L2" },
      { "tag": "blowjob_face",     "ja": "フェラ顔", "level": "L2" },
      { "tag": "ahegao",           "ja": "アヘ顔", "level": "L2" },
      { "tag": "rolling_eyes",     "ja": "目を白目にむく", "level": "L2" },
      { "tag": "drooling",         "ja": "よだれを垂らす", "level": "L2" },
      { "tag": "orgasmic",         "ja": "絶頂の表情", "level": "L2" },
      { "tag": "crying_pleasure",  "ja": "快楽泣き", "level": "L2" },
      { "tag": "biting_sheet",     "ja": "シーツを噛む", "level": "L2" },
      { "tag": "arched_back_face", "ja": "のけぞり絶頂顔", "level": "L2" },
      { "tag": "sweaty_face",      "ja": "汗だくの顔", "level": "L2" },
      { "tag": "post_orgasm_daze", "ja": "絶頂後放心顔", "level": "L2" },
      { "tag": "blissful_smile",   "ja": "恍惚スマイル", "level": "L2" },
      { "tag": "fainting_face",    "ja": "失神顔",       "level": "L3" },
    
      { "tag": "terror",           "ja": "恐怖", "level": "L3" },
      { "tag": "agony",            "ja": "苦悶", "level": "L3" },
      { "tag": "crying_screaming", "ja": "泣き叫び", "level": "L3" },
      { "tag": "painful_pleasure", "ja": "苦痛混じりの快楽", "level": "L3" },
      { "tag": "broken_expression","ja": "壊れた表情", "level": "L3" },
    
      { "tag": "shy_smile",        "ja": "恥じらい笑顔", "level": "L1" },
      { "tag": "averted_gaze",     "ja": "目を逸らす", "level": "L1" },
      { "tag": "wink",             "ja": "ウィンク", "level": "L1" },
      { "tag": "smug_grin",        "ja": "ドヤ顔/勝ち誇り笑み", "level": "L1" },
      { "tag": "upturned_eyes",    "ja": "上目遣い", "level": "L1" },
      { "tag": "gasp",             "ja": "息を呑む/はっとする", "level": "L1" },
      { "tag": "nosebleed",        "ja": "鼻血（興奮の定番演出）", "level": "L1" },
      { "tag": "sweat_drop",       "ja": "冷や汗（焦り/動揺）", "level": "L1" },
    
      { "tag": "lustful",          "ja": "いやらしい表情", "level": "L2" },
      { "tag": "horny_face",       "ja": "発情顔", "level": "L2" },
      { "tag": "droopy_eyes",      "ja": "とろん目（脱力寄り）", "level": "L2" },
      { "tag": "slack_jaw",        "ja": "口半開き", "level": "L2" },
      { "tag": "licking_lips",     "ja": "舌なめずり", "level": "L2" },
      { "tag": "biting_finger",    "ja": "指を噛む/咥える", "level": "L2" },
      { "tag": "heart_eyes",       "ja": "ハート目", "level": "L2" },
      { "tag": "glazed_eyes",      "ja": "うつろ目", "level": "L2" },
      { "tag": "tongue_heart",     "ja": "ハート舌", "level": "L2" },
    
      { "tag": "biting_lip_pain",  "ja": "苦痛に唇を噛む", "level": "L3" },
      { "tag": "forced_smile",     "ja": "無理やりの笑顔", "level": "L3" },
      { "tag": "orgasm_face_closeup",      "ja": "絶頂時の顔アップ", "level": "L2" },
      { "tag": "afterglow_face",           "ja": "事後の恍惚顔アップ", "level": "L1" },
      { "tag": "spoken_text",   "ja": "普通の吹き出し（セリフ強調）", "level": "L1" },
      { "tag": "spoken_heart",  "ja": "ハート付き吹き出し",           "level": "L1" },
      { "tag": "spoken_moan",   "ja": "擬音・あえぎ声吹き出し",       "level": "L2" },
      { "tag": "spoken_symbol", "ja": "記号（！？など）入り吹き出し", "level": "L1" }
    ],

      "exposure": [
      { "tag": "mild_cleavage", "ja": "控えめな胸元", "level": "L1" },
      { "tag": "off_shoulder",  "ja": "オフショルダー", "level": "L1" },
      { "tag": "bare_back",     "ja": "背中見せ", "level": "L1" },
      { "tag": "leggy",         "ja": "脚見せ", "level": "L1" },
      { "tag": "short_skirt",   "ja": "ミニスカ", "level": "L1" },
      { "tag": "tight_clothes", "ja": "ぴったり服", "level": "L1" },
      { "tag": "wet_clothes",   "ja": "濡れた服", "level": "L2" },
      { "tag": "see_through",   "ja": "シースルー", "level": "L2" },
      { "tag": "sideboob",      "ja": "サイド露出", "level": "L2" },
      { "tag": "underboob",     "ja": "アンダー露出", "level": "L2" },
      { "tag": "cameltoe",      "ja": "股間の形が浮き出る(キャメルトゥ)", "level": "L2" },
      { "tag": "panty_peek",    "ja": "パンチラ", "level": "L2" },
      { "tag": "cleavage_window", "ja": "胸元カットアウト", "level": "L2" },
      { "tag": "topless",       "ja": "上半身裸", "level": "L2" },
      { "tag": "bottomless",    "ja": "下半身裸", "level": "L2" },
      { "tag": "nude",          "ja": "全裸", "level": "L2" },
      { "tag": "nip_slip",  "ja": "乳首チラ", "level": "L1" },
      { "tag": "ass_peek",  "ja": "尻チラ（パンツずらし）", "level": "L1" },
      { "tag": "visible_pubic_hair", "ja": "陰毛が見えている", "level": "L2" },
      { "tag": "pubic_hair_peek",  "ja": "陰毛チラ見え", "level": "L1" },
      { "tag": "pubic_hair_out",   "ja": "下着からはみ毛", "level": "L2" },
      { "tag": "exposed_genitals", "ja": "性器露出", "level": "L3" },
      { "tag": "lewd_outfit",   "ja": "卑猥な衣装", "level": "L3" },
      { "tag": "bondage_exposure", "ja": "拘束露出", "level": "L3" },
      { "tag": "transparent_bra",     "ja": "透けブラ",         "level": "L1" },
      { "tag": "transparent_panties", "ja": "透けパンツ",       "level": "L1" },
      { "tag": "sheer_stockings",     "ja": "シースルーストッキング", "level": "L1" },
      { "tag": "wet_see_through",     "ja": "濡れて透ける服",   "level": "L2" },
      { "tag": "white_shirt_see_through","ja": "白シャツ透け",  "level": "L2" },
      { "tag": "lingerie_see_through","ja": "透けランジェリー", "level": "L2" },
      { "tag": "full_transparent_outfit", "ja": "全身透け衣装", "level": "L3" },
      { "tag": "mesh_outfit",         "ja": "メッシュ透け衣装", "level": "L2" },
      { "tag": "latex_transparent",   "ja": "透明ラバー衣装",   "level": "L3" },
      { "tag": "underboob_window",  "ja": "下乳カットアウト衣装", "level": "L2" },
      { "tag": "underboob_peek",    "ja": "下乳チラ見え",         "level": "L1" },
      { "tag": "side_underboob",    "ja": "横から下乳露出",       "level": "L2" },
      { "tag": "crop_top_underboob","ja": "丈の短いトップスで下乳", "level": "L1" },
      { "tag": "lifted_top",        "ja": "服をめくって下乳露出", "level": "L2" }
    ],

      "situation": [
      { "tag": "mirror_selfie", "ja": "鏡越しの自撮り", "level": "L1" },
      { "tag": "after_shower", "ja": "入浴後・濡れ髪", "level": "L1" },
      { "tag": "towel_wrap", "ja": "タオルで巻く", "level": "L1" },
      { "tag": "sauna_steam", "ja": "サウナ・湯気", "level": "L1" },
      { "tag": "sunbathing", "ja": "日光浴", "level": "L1" },
      { "tag": "in_bed_sheets", "ja": "シーツに包まれて", "level": "L2" },
      { "tag": "zipper_down", "ja": "ジッパー下げ", "level": "L2" },
      { "tag": "censored_bars", "ja": "モザイク/黒帯", "level": "L2" },
      { "tag": "light_beam_censor", "ja": "光線検閲", "level": "L2" },
      { "tag": "sticker_censor", "ja": "スタンプ隠し", "level": "L1" },
      { "tag": "shibari", "ja": "緊縛", "level": "L2" },
      { "tag": "toilet_play",    "ja": "トイレプレイ", "level": "L3" },
      { "tag": "caught_in_the_act", "ja": "行為中に見つかる", "level": "L2" },
      { "tag": "public_toilet",     "ja": "公衆トイレ",       "level": "L2" },
      { "tag": "locker_room",       "ja": "ロッカールーム",   "level": "L1" },
      { "tag": "voyeur_camera",     "ja": "盗撮カメラ視点",   "level": "L3" },
      { "tag": "bedroom", "ja": "ベッドの上", "level": "L1" },
      { "tag": "classroom", "ja": "教室", "level": "L1" },
      { "tag": "rooftop", "ja": "屋上", "level": "L1" },
      { "tag": "bathroom", "ja": "バスルーム", "level": "L1" },
      { "tag": "hot_spring", "ja": "温泉", "level": "L1" },
      { "tag": "poolside", "ja": "プールサイド", "level": "L1" },
      { "tag": "beach", "ja": "ビーチ", "level": "L1" },
      { "tag": "train", "ja": "電車内", "level": "L2" },
      { "tag": "office", "ja": "オフィス", "level": "L1" },
      { "tag": "elevator", "ja": "エレベーター", "level": "L1" },
      { "tag": "alley", "ja": "路地裏", "level": "L2" },
      { "tag": "cage", "ja": "檻の中", "level": "L3" },
      { "tag": "dungeon", "ja": "地下牢", "level": "L3" },
      { "tag": "stage_performance", "ja": "ステージ演出", "level": "L2" },
      { "tag": "sweat",        "ja": "汗（むわっとした表現）", "level": "L1" },
      { "tag": "steam",        "ja": "白いモヤ・蒸気",         "level": "L1" },
      { "tag": "sweaty_body",       "ja": "汗だくの体",        "level": "L1" },
      { "tag": "sweaty_face",       "ja": "汗をかいた顔",      "level": "L1" },
      { "tag": "sweaty_clothes",    "ja": "汗で濡れた服",      "level": "L2" },
      { "tag": "sweat_drops",       "ja": "滴る汗",            "level": "L2" },
      { "tag": "after_exercise",    "ja": "運動後の汗",        "level": "L1" },
      { "tag": "summer_heat",       "ja": "夏の暑さで汗",      "level": "L1" },
      { "tag": "crowded_train_heat","ja": "満員電車で汗だく",  "level": "L2" },
      { "tag": "intense_sex_sweat", "ja": "行為中の汗だく",    "level": "L2" },
      { "tag": "selfie", "ja": "自撮り（露出あり）", "level": "L1" },
      { "tag": "masked_selfie", "ja": "口マスク＋自撮り", "level": "L1" }
    ],

      "lighting": [
        { "tag": "softbox", "ja": "ソフトライト", "level": "L1" },
        { "tag": "rim_light", "ja": "リムライト", "level": "L1" },
        { "tag": "backlit", "ja": "逆光シルエット", "level": "L1" },
        { "tag": "window_glow", "ja": "窓明かり/夕暮れ", "level": "L1" },
        { "tag": "golden_hour", "ja": "ゴールデンアワー", "level": "L1" },
        { "tag": "neon", "ja": "ネオン光", "level": "L1" },
        { "tag": "candlelight", "ja": "キャンドル", "level": "L1" },
        { "tag": "low_key", "ja": "ローキー", "level": "L1" },
        { "tag": "hard_light", "ja": "ハードライト", "level": "L1" },
        { "tag": "colored_gels", "ja": "カラーフィルタ", "level": "L1" },
        { "tag": "film_noir", "ja": "フィルム・ノワール", "level": "L1" },
        { "tag": "dappled_light", "ja": "木漏れ日/斑光", "level": "L1" },
        { "tag": "spotlight", "ja": "スポットライト", "level": "L1" },
        { "tag": "moody", "ja": "ムーディ", "level": "L1" },
        { "tag": "red_light",        "ja": "赤色照明（官能的）", "level": "L1" },
        { "tag": "pink_glow",        "ja": "ピンク光（ラブホテル風）", "level": "L1" },
        { "tag": "blue_neon",        "ja": "青ネオン光（妖艶）", "level": "L1" },
        { "tag": "underlight_erotic","ja": "下からのライト（フェティッシュ）", "level": "L1" },
        { "tag": "moody_bedroom",    "ja": "ベッドルームの薄暗い照明", "level": "L1" },
        { "tag": "blacklight",      "ja": "ブラックライト",   "level": "L2" },
        { "tag": "flashlight_pov",  "ja": "懐中電灯光POV",   "level": "L3" },
      
        { "tag": "spotlight_focus",  "ja": "スポットライトで局所強調", "level": "L2" },
        { "tag": "silhouette_light", "ja": "逆光シルエットで輪郭強調", "level": "L2" },
        { "tag": "wet_skin_glow",    "ja": "濡れ肌に光が反射", "level": "L2" },
        { "tag": "oily_reflection",  "ja": "オイル/ローション光沢", "level": "L2" },
        { "tag": "strobe_effect",    "ja": "ストロボ光（乱交/クラブ風）", "level": "L2" },
      
        { "tag": "horror_red_light", "ja": "赤黒い照明（凌辱/ホラー）", "level": "L3" },
        { "tag": "fetish_spotlight", "ja": "局部だけを照らす光", "level": "L3" },
        { "tag": "dungeon_torch",    "ja": "地下牢/拷問部屋の松明光", "level": "L3" }
      ],

      "pose": [
        { "tag": "standing",        "ja": "立ち姿",            "level": "L1" },
        { "tag": "sitting",         "ja": "座る",              "level": "L1" },
        { "tag": "lying_down",      "ja": "横たわる",          "level": "L1" },
        { "tag": "kneeling",        "ja": "跪く",              "level": "L1" },
        { "tag": "seiza_pose",      "ja": "正座",              "level": "L1" },
        { "tag": "crouching",       "ja": "しゃがむ",          "level": "L1" },
        { "tag": "bent_over",       "ja": "前屈み",            "level": "L1" },
        { "tag": "arched_back",     "ja": "背中を反らす",      "level": "L1" },
      
        { "tag": "spread_legs",     "ja": "脚を広げる",        "level": "L2" },
        { "tag": "frog_pose",       "ja": "M字開脚",           "level": "L2" },
        { "tag": "cross_legged",    "ja": "あぐら",            "level": "L1" },
        { "tag": "one_knee_up",     "ja": "片膝立て",          "level": "L1" },
        { "tag": "hand_on_hips",    "ja": "腰に手を当てる",    "level": "L1" },
        { "tag": "covering_chest",  "ja": "胸を隠す",          "level": "L1" },
        { "tag": "covering_crotch", "ja": "股間を隠す",        "level": "L1" },
        { "tag": "face_covering",   "ja": "顔を隠す",          "level": "L1" },

        { "tag": "labia_spread",     "ja": "小陰唇を広げる",             "level": "L2" },
        { "tag": "pussy_spread",     "ja": "くぱぁ（性器開き）",          "level": "L2" },
        { "tag": "gaping_vagina",    "ja": "拡張くぱぁ（大きく開く）",    "level": "L3" },
        { "tag": "spread_pussy",      "ja": "くぱぁ（大開脚）",      "level": "L2" },
      
        { "tag": "on_all_fours",    "ja": "四つん這い",        "level": "L2" },
        { "tag": "against_wall",    "ja": "壁に寄りかかる",    "level": "L1" },
        { "tag": "press_against_wall","ja": "壁ドンされる姿勢", "level": "L2" },
      
        { "tag": "missionary_leg_hold",       "ja": "正常位・足を持ち上げる",         "level": "L2" },
        { "tag": "missionary_leg_on_shoulder","ja": "正常位・足を肩に乗せる",         "level": "L2" },
        { "tag": "missionary_leg_spread",     "ja": "正常位・足を大きく広げられる",   "level": "L2" },
        
        { "tag": "cowgirl_leg_grab",          "ja": "騎乗位・足を持たれる",           "level": "L2" },
        { "tag": "reverse_cowgirl_leg_hold",  "ja": "背面騎乗位・足を掴まれる",       "level": "L2" },
        
        { "tag": "legs_over_shoulders",       "ja": "両脚を肩にかけられる",           "level": "L3" },
        { "tag": "legs_pinned",               "ja": "脚を押さえつけられる体位",       "level": "L3" },
        { "tag": "legs_spread_holding",       "ja": "足を持って強制的に広げられる",   "level": "L3" },
        
        { "tag": "standing_leg_up",           "ja": "立位・片脚持ち上げ体位",         "level": "L2" },
        { "tag": "standing_double_leg_hold",  "ja": "立位・両脚抱え上げ体位",         "level": "L3" },

        { "tag": "doggy_leg_lift",         "ja": "バック・片脚上げ",          "level": "L2" },
        { "tag": "doggy_leg_hold",         "ja": "バック・脚を持たれる",      "level": "L2" },
        { "tag": "reverse_doggy_flat",     "ja": "腹這い・押さえつけバック",  "level": "L3" },
        
        { "tag": "standing_leg_hold",      "ja": "立位・片脚持ち上げ",        "level": "L2" },
        { "tag": "standing_carry",         "ja": "立位・抱き上げ体位",        "level": "L3" },
        { "tag": "against_wall_standing",  "ja": "壁押し付け立位",            "level": "L2" },
        
        { "tag": "spooning_leg_lift",      "ja": "添い寝位・片脚持ち上げ",    "level": "L2" },
        { "tag": "reverse_spooning",       "ja": "背面添い寝位",              "level": "L2" },
        
        { "tag": "lotus_leg_wrap",         "ja": "蓮華座・足を絡める",        "level": "L2" },
        
        { "tag": "lap_sitting_facing",     "ja": "膝上騎乗・対面",            "level": "L2" },
        { "tag": "lap_sitting_reverse",    "ja": "膝上騎乗・背面",            "level": "L2" },
        
        { "tag": "chair_reverse_cowgirl",  "ja": "椅子上・背面騎乗位",        "level": "L2" },
        { "tag": "chair_sideways",         "ja": "椅子上・横向き騎乗位",      "level": "L2" },
        
        { "tag": "tabletop_doggy",         "ja": "机の上バック体位",          "level": "L2" },
        { "tag": "tabletop_spread",        "ja": "机の上・脚を広げる体位",    "level": "L3" },

      
        { "tag": "sixty_nine",      "ja": "69",                "level": "L2" },
        { "tag": "facesitting",     "ja": "顔面騎乗位",        "level": "L2" },
        { "tag": "riding_face",     "ja": "顔に跨る",          "level": "L2" },
        { "tag": "breast_rubbing",  "ja": "胸を擦り合わせる",  "level": "L2" },
        { "tag": "tribbing",        "ja": "トリビング",         "level": "L2" },
        { "tag": "scissoring",      "ja": "シザリング",         "level": "L2" },
        { "tag": "face_to_face",    "ja": "対面密着座位",      "level": "L2" },
      
        { "tag": "pile_driver",     "ja": "パイルドライバー",  "level": "L3" },
        { "tag": "reverse_pile_driver","ja": "逆パイルドライバー","level": "L3" },
        { "tag": "amazon_position", "ja": "アマゾン体位",       "level": "L3" },
        { "tag": "butterfly_position","ja": "バタフライ体位",   "level": "L2" },
        { "tag": "standing_split",  "ja": "片脚上げ立位",       "level": "L2" },
        { "tag": "bridge_pose",     "ja": "ブリッジ体位",      "level": "L2" },
        { "tag": "wheelbarrow",     "ja": "手押し車体位",      "level": "L3" },
      
        { "tag": "double_penetration","ja": "ダブル挿入",       "level": "L3" },
        { "tag": "triple_penetration","ja": "トリプル挿入",     "level": "L3" },
        { "tag": "gangbang_pose",   "ja": "乱交体位",          "level": "L3" },
        { "tag": "double_vaginal",  "ja": "二穴同時（膣）",    "level": "L3" },
        { "tag": "double_anal",     "ja": "二穴同時（アナル）","level": "L3" },
        { "tag": "vaginal_anal",    "ja": "膣アナル同時挿入",  "level": "L3" },
        { "tag": "airtight_pose",   "ja": "エアタイト体位",    "level": "L3" },
      
        { "tag": "hands_tied",      "ja": "手を縛られる",      "level": "L3" },
        { "tag": "legs_tied",       "ja": "脚を縛られる",      "level": "L3" },
        { "tag": "hogtied",         "ja": "後手拘束",          "level": "L3" },
        { "tag": "forced_kneeling", "ja": "強制跪き",          "level": "L3" },
        { "tag": "spanking_pose",   "ja": "お仕置き体勢",      "level": "L3" },
        { "tag": "whipping_pose",   "ja": "鞭打ち体勢",        "level": "L2" },
        { "tag": "suspension_bondage","ja": "吊り緊縛",        "level": "L2" },
        { "tag": "spread_eagle",    "ja": "大の字拘束",        "level": "L2" },
        { "tag": "forced_spread_eagle","ja": "強制大の字拘束", "level": "L3" },
        { "tag": "stocks_pose",     "ja": "拘束台固定",        "level": "L2" },
        { "tag": "collared_pose",   "ja": "首輪をつけられる",  "level": "L3" },
        { "tag": "leashed_pose",    "ja": "リードで引かれる",  "level": "L3" },
        { "tag": "public_exposure_pose","ja": "人前で晒される","level": "L3" },
        { "tag": "cage_pose",       "ja": "檻の中に拘束",      "level": "L3" },
        { "tag": "side_missionary",       "ja": "側位（横向き正常位）",       "level": "L2" },
        { "tag": "reverse_side_missionary","ja": "逆側位（背後から横向き）",   "level": "L2" },
        
        { "tag": "cowgirl_forward_lean",  "ja": "騎乗位・前傾姿勢",            "level": "L2" },
        { "tag": "cowgirl_back_lean",     "ja": "騎乗位・反り返り",            "level": "L2" },
        { "tag": "reverse_cowgirl_low",   "ja": "背面騎乗位・低く座る",        "level": "L2" },
        
        { "tag": "doggy_flat",            "ja": "バック・ベッドに押し付け",    "level": "L2" },
        { "tag": "doggy_standing",        "ja": "立位バック（立ちバック）",    "level": "L2" },
        { "tag": "doggy_over_table",      "ja": "机に手をついてバック",        "level": "L2" },
        
        { "tag": "reverse_spooning_leg_hold", "ja": "背面添い寝・片脚持ち上げ","level": "L2" },
        { "tag": "sideways_leg_hold",     "ja": "横向き・脚を持ち上げる体位", "level": "L2" },
        
        { "tag": "chair_forward",         "ja": "椅子上・前抱き体位",          "level": "L2" },
        { "tag": "chair_doggy",           "ja": "椅子上・後背位",              "level": "L2" },
        
        { "tag": "against_wall_leg_up",   "ja": "壁押し付け・片脚上げ",        "level": "L3" },
        { "tag": "against_wall_carry",    "ja": "壁押し付け・持ち上げ体位",    "level": "L3" },
        
        { "tag": "prone_bone",            "ja": "うつ伏せ体位（寝バック）",   "level": "L2" },
        
        { "tag": "lap_sitting_sideways",  "ja": "膝上・横向き座位",            "level": "L2" },
        
        { "tag": "reverse_bridge",        "ja": "逆ブリッジ体位",              "level": "L3" },
        { "tag": "handstand_position",    "ja": "逆立ち体位",                  "level": "L3" },
        
        { "tag": "multiple_partner_chain","ja": "連結体位（複数人繋がる）",   "level": "L3" },
        { "tag": "daisuki_hold",         "ja": "だいしゅきホールド（足絡め密着）", "level": "L3" },
        { "tag": "missionary_kissing",   "ja": "正常位でキス",                    "level": "L2" },
        { "tag": "cowgirl_kissing",      "ja": "騎乗位でキス",                    "level": "L2" },
        { "tag": "spooning_kissing",     "ja": "添い寝位でキス",                  "level": "L2" },
        { "tag": "lap_sitting_kissing",  "ja": "膝上座位でキス",                  "level": "L2" },
        { "tag": "against_wall_kissing", "ja": "壁ドンしながらキス",              "level": "L2" },
        { "tag": "reverse_cowgirl_kiss", "ja": "背面騎乗位で振り返りキス",        "level": "L3" }

      ],
    
    "accessories": [
      { "tag": "choker",            "ja": "チョーカー",          "level": "L1" },
      { "tag": "eye_mask",          "ja": "アイマスク",          "level": "L1" },
      { "tag": "feather_tickler",   "ja": "羽根の小道具",        "level": "L1" },
      { "tag": "handcuffs_toy",     "ja": "おもちゃ手錠",        "level": "L1" },
      { "tag": "vibrating_egg",     "ja": "ローター/電マ",       "level": "L1" },
      { "tag": "condom",            "ja": "コンドーム",          "level": "L1" },
      { "tag": "lubricant_bottle",  "ja": "ローションボトル",    "level": "L1" },
      { "tag": "lingerie_set",      "ja": "ランジェリー小物",    "level": "L1" },
      { "tag": "bunny_ears",        "ja": "バニー耳カチューシャ","level": "L1" },
      { "tag": "cat_ears",          "ja": "猫耳カチューシャ",    "level": "L1" },
      { "tag": "maid_headband",     "ja": "メイドカチューシャ",  "level": "L1" },
      { "tag": "nurse_hat",         "ja": "ナースキャップ",      "level": "L1" },
      { "tag": "school_uniform_tie","ja": "制服ネクタイ/リボン", "level": "L1" },
    
      { "tag": "gag",               "ja": "ボールギャグ",        "level": "L2" },
      { "tag": "ring_gag",          "ja": "リングギャグ",        "level": "L2" },
      { "tag": "blindfold",         "ja": "目隠し",              "level": "L2" },
      { "tag": "handcuffs",         "ja": "金属手錠",            "level": "L2" },
      { "tag": "rope_bondage",      "ja": "縄・緊縛",            "level": "L2" },
      { "tag": "collar_and_leash",  "ja": "首輪とリード",        "level": "L2" },
      { "tag": "nipple_clamps",     "ja": "乳首クリップ",        "level": "L2" },
      { "tag": "butt_plug",         "ja": "アナルプラグ",        "level": "L2" },
      { "tag": "anal_beads",     "ja": "アナルビーズ",       "level": "L2" },
      { "tag": "rope_harness",   "ja": "縄ボディハーネス",   "level": "L2" },
      { "tag": "vibrator",          "ja": "バイブ",              "level": "L2" },
      { "tag": "dildo",             "ja": "ディルド",            "level": "L2" },
      { "tag": "strap_on",          "ja": "ストラップオン",      "level": "L2" },
      { "tag": "restraints_frame",  "ja": "拘束フレーム",        "level": "L2" },
      { "tag": "paddle",            "ja": "パドル",              "level": "L2" },
    
      { "tag": "whip",              "ja": "鞭",                  "level": "L3" },
      { "tag": "electro_toy",       "ja": "電気責め玩具",        "level": "L3" },
      { "tag": "speculum",          "ja": "開脚器/拡張器具",     "level": "L3" },
      { "tag": "iron_mask",         "ja": "拘束マスク",          "level": "L3" },
      // 6. 道具・アイテム（拡張）
      { "tag": "love_potion", "ja": "媚薬", "level": "L2" },
      { "tag": "aphrodisiac", "ja": "催淫剤", "level": "L2" },
      { "tag": "massage_oil", "ja": "マッサージオイル", "level": "L1" },
      { "tag": "edible_underwear", "ja": "食べられる下着", "level": "L2" },
      { "tag": "ice_cube_play", "ja": "氷プレイ", "level": "L1" },
      { "tag": "candle_wax", "ja": "ロウソクプレイ", "level": "L2" },
      { "tag": "remote_vibrator", "ja": "リモコンバイブ", "level": "L2" },
      { "tag": "chastity_belt", "ja": "貞操帯", "level": "L3" },
      { "tag": "dog_ears",        "ja": "犬耳カチューシャ", "level": "L1" },
      { "tag": "fox_ears",        "ja": "狐耳カチューシャ", "level": "L1" },
      { "tag": "wolf_ears",       "ja": "狼耳カチューシャ", "level": "L1" },
      { "tag": "bear_ears",       "ja": "熊耳カチューシャ", "level": "L1" },
      { "tag": "sheep_ears",      "ja": "羊耳カチューシャ", "level": "L1" },
      { "tag": "deer_antlers",    "ja": "鹿の角アクセ",      "level": "L1" },
      { "tag": "dragon_horns",    "ja": "ドラゴンの角",      "level": "L1" },
      { "tag": "halo",            "ja": "天使の輪",          "level": "L1" },
      { "tag": "devil_horns",     "ja": "悪魔の角カチューシャ","level": "L1" },
      { "tag": "angel_wings",     "ja": "天使の翼アクセ",    "level": "L1" },
      { "tag": "devil_wings",     "ja": "悪魔の翼アクセ",    "level": "L1" },
      { "tag": "tail_accessory",  "ja": "しっぽアクセ",      "level": "L1" },
      { "tag": "pubic_tattoo",      "ja": "淫紋（恥丘タトゥー）", "level": "L2" }
        ],
    
    "outfit": [
      { "tag": "bunny_suit",         "ja": "バニースーツ",             "level": "L1" },
      { "tag": "nurse_uniform",      "ja": "ナース服",                 "level": "L1" },
      { "tag": "maid_outfit",        "ja": "メイド服（えっち仕様）",    "level": "L1" },
      { "tag": "school_swimsuit",    "ja": "スクール水着",             "level": "L1" },
      { "tag": "sailor_uniform_r18", "ja": "セーラー服（えっち仕様）",  "level": "L1" },
      { "tag": "blazer_uniform_r18", "ja": "ブレザー制服（えっち仕様）","level": "L1" },
      { "tag": "gym_bloomers",       "ja": "体操着ブルマ",             "level": "L1" },
      { "tag": "idol_costume_r18",   "ja": "アイドル衣装（えっち仕様）","level": "L1" },
      { "tag": "nude_apron",      "ja": "裸エプロン",         "level": "L2" },
      { "tag": "gym_swimsuit_r18","ja": "競泳水着（えっち仕様）", "level": "L2" },
    
      { "tag": "bikini",             "ja": "ビキニ",                  "level": "L2" },
      { "tag": "micro_bikini",       "ja": "マイクロビキニ",          "level": "L2" },
      { "tag": "string_bikini",      "ja": "紐ビキニ",                "level": "L2" },
      { "tag": "sling_bikini",       "ja": "スリングショットビキニ",  "level": "L2" },
      { "tag": "wet_swimsuit",       "ja": "濡れた水着",              "level": "L2" },
      { "tag": "nipple_cover_bikini","ja": "ニップルカバービキニ",    "level": "L2" },
      { "tag": "crotchless_swimsuit","ja": "クロッチレス水着",        "level": "L2" },
      { "tag": "bodypaint_swimsuit", "ja": "ボディペイント水着",      "level": "L2" },
    
      { "tag": "bondage_outfit",     "ja": "ボンデージ衣装",          "level": "L2" },
      { "tag": "latex_suit",         "ja": "ラバースーツ",            "level": "L2" },
      { "tag": "body_harness",       "ja": "ボディハーネス",          "level": "L2" },
      { "tag": "bondage_straps",     "ja": "拘束ベルト衣装",          "level": "L2" },
      { "tag": "fetish_catsuit",     "ja": "フェティッシュ全身スーツ","level": "L2" },
      { "tag": "gimp_suit",          "ja": "ギンプスーツ",            "level": "L2" },
    
      { "tag": "transparent_dress",  "ja": "シースルードレス",        "level": "L2" },
      { "tag": "open_crotch_pants",  "ja": "股開きパンツ",            "level": "L2" },
      { "tag": "stripper_outfit",    "ja": "ストリッパー衣装",        "level": "L3" },
      { "tag": "stripper_stage",     "ja": "ストリップ舞台衣装",      "level": "L3" },
    
      { "tag": "cheerleader_outfit", "ja": "チアリーダー衣装",        "level": "L1" },
      { "tag": "idol_stage_costume", "ja": "ステージアイドル衣装",    "level": "L1" },
      { "tag": "cosplay_police",     "ja": "婦警コスプレ",            "level": "L1" },
      { "tag": "cosplay_teacher",    "ja": "女教師コスプレ",          "level": "L1" },
      { "tag": "cosplay_office",     "ja": "OLスーツ（えっち仕様）",   "level": "L1" },
    
      { "tag": "fantasy_mage",       "ja": "魔法使い衣装（えっち仕様）","level": "L2" },
      { "tag": "dark_sorceress",     "ja": "ダークソーサレス衣装",     "level": "L2" },
      { "tag": "priestess_robe",     "ja": "巫女/神官ローブ（えっち仕様）","level": "L1" },
      { "tag": "succubus_outfit",    "ja": "サキュバス衣装",          "level": "L2" },
      { "tag": "demon_armor",        "ja": "魔族風アーマー",          "level": "L2" },
      { "tag": "elf_costume",        "ja": "エルフ衣装（えっち仕様）", "level": "L1" },
      { "tag": "warrior_armor_r18",  "ja": "女戦士アーマー（露出多め）","level": "L2" },
      { "tag": "barbarian_bikini",   "ja": "バーバリアンビキニアーマー","level": "L2" },
      { "tag": "princess_dress_r18", "ja": "姫ドレス（えっち仕様）",    "level": "L1" },
      { "tag": "magical_girl_r18",   "ja": "魔法少女衣装（えっち仕様）","level": "L1" },
      { "tag": "witch_outfit",       "ja": "魔女衣装（セクシー）",      "level": "L1" }
    ],
    "underwear": [
      { "tag": "bra_off",            "ja": "ブラなし",           "level": "L2" },
      { "tag": "bra_unhooked",       "ja": "ブラ外しかけ",       "level": "L1" },
      { "tag": "bra_pulled_aside",   "ja": "ブラずらし",         "level": "L2" },
      { "tag": "open_cup_bra",       "ja": "乳首みせブラ",         "level": "L2" },
    
      { "tag": "panties_off",        "ja": "パンツなし",         "level": "L2" },
      { "tag": "panties_pulled_aside","ja": "パンツずらし",       "level": "L2" },
      { "tag": "crotchless_panties", "ja": "股あきパンツ",       "level": "L2" },
    
      { "tag": "lingerie_white",  "ja": "白ランジェリーセット",  "level": "L1" },
      { "tag": "lingerie_black",  "ja": "黒ランジェリーセット",  "level": "L1" },
      { "tag": "lingerie_red",    "ja": "赤ランジェリーセット",  "level": "L1" },
      { "tag": "lingerie_pink",   "ja": "ピンクランジェリーセット","level": "L1" },
      { "tag": "lingerie_blue",   "ja": "青ランジェリーセット",   "level": "L1" },
      { "tag": "lingerie_purple", "ja": "紫ランジェリーセット",   "level": "L1" },
      { "tag": "lingerie_beige",  "ja": "ベージュランジェリーセット","level": "L1" },
    
      { "tag": "lace_bra",       "ja": "レースブラ",           "level": "L1" },
      { "tag": "lace_panties",   "ja": "レースショーツ",       "level": "L1" },
      { "tag": "transparent_lingerie","ja": "透けランジェリー", "level": "L2" },
    
      { "tag": "boyshorts",      "ja": "ボクサーショーツ",     "level": "L1" },
      { "tag": "string_panties", "ja": "Tバック",             "level": "L2" },
      { "tag": "sheer_panties",  "ja": "シースルーショーツ",   "level": "L2" },
    
      { "tag": "sports_bra",     "ja": "スポーツブラ",         "level": "L1" },
      { "tag": "cupless_corset", "ja": "胸あきコルセット",     "level": "L2" },
    
      { "tag": "stockings_black","ja": "黒ストッキング",      "level": "L1" },
      { "tag": "stockings_white","ja": "白ストッキング",      "level": "L1" },
      { "tag": "stockings_fishnet","ja": "網ストッキング",    "level": "L2" },
      { "tag": "thighhighs",     "ja": "ニーハイソックス",     "level": "L1" },
      { "tag": "garter_belt",    "ja": "ガーターベルト",       "level": "L2" },
    
      { "tag": "camisole",       "ja": "キャミソール",         "level": "L1" },
      { "tag": "slip_dress",     "ja": "スリップドレス",       "level": "L1" },
      { "tag": "babydoll",       "ja": "ベビードール",         "level": "L1" },
      { "tag": "negligee",       "ja": "ネグリジェ",           "level": "L1" },
      { "tag": "satin_robe",     "ja": "サテンローブ",         "level": "L1" },
      { "tag": "silk_nightgown", "ja": "シルクナイトガウン",   "level": "L1" },
    
      { "tag": "bondage_lingerie","ja": "ボンデージ下着",      "level": "L2" },
      { "tag": "harness_underwear","ja": "ハーネス下着",        "level": "L2" },
      { "tag": "fundoshi",       "ja": "ふんどし",             "level": "L1" },
      { "tag": "sarashi",        "ja": "さらし",               "level": "L1" },
      { "tag": "juban",          "ja": "襦袢",                 "level": "L1" },
      { "tag": "hadajuban",      "ja": "肌襦袢",               "level": "L1" },
      { "tag": "koshimaki",      "ja": "腰巻き",               "level": "L1" },
    
      { "tag": "latex_underwear","ja": "ラテックス下着",       "level": "L2" },
      { "tag": "open_bust_teddy","ja": "胸あきテディ",         "level": "L3" },
      { "tag": "chain_lingerie", "ja": "チェーン下着",         "level": "L3" },
    
      { "tag": "strapless_bra",   "ja": "肩ひもなしブラ",       "level": "L1" },
      { "tag": "pushup_bra",      "ja": "寄せ上げブラ",         "level": "L1" },
      { "tag": "g_string",        "ja": "極細Tバック",         "level": "L2" },
      { "tag": "highwaist_panties","ja": "ハイウエストショーツ","level": "L1" },
      { "tag": "cotton_underwear","ja": "コットン下着",        "level": "L1" },
      { "tag": "satin_lingerie",  "ja": "サテン下着",           "level": "L1" },
      { "tag": "pearl_panties",   "ja": "パール付きショーツ",   "level": "L2" },
      { "tag": "strap_underwear", "ja": "ストラップ下着",       "level": "L2" }
    ],
        "body": [
      { "tag": "flat_chest", "ja": "貧乳", "level": "L1" },
      { "tag": "small_breasts", "ja": "小胸", "level": "L1" },
      { "tag": "average_bust", "ja": "標準バスト", "level": "L1" },
      { "tag": "big_breasts", "ja": "爆乳", "level": "L2" },
      { "tag": "huge_breasts", "ja": "超乳", "level": "L2" },
      { "tag": "milky_breasts", "ja": "母乳体型", "level": "L2" },
      { "tag": "lactating", "ja": "母乳分泌", "level": "L2" },
      { "tag": "pregnant_body", "ja": "妊娠体型（お腹ふくらみ）", "level": "L2" },
      { "tag": "pregnant_belly", "ja": "孕み腹", "level": "L2" },
      { "tag": "pregnant",          "ja": "ボテ腹（妊娠体型）",   "level": "L2" },
      { "tag": "succubus_body",   "ja": "淫魔体型",    "level": "L2" },
      { "tag": "emaciated_body",  "ja": "やつれ体型",  "level": "L3" },
      { "tag": "postpartum_body", "ja": "産後体型", "level": "L2" },
      { "tag": "chubby", "ja": "ぽっちゃり", "level": "L1" },
      { "tag": "plump", "ja": "ふくよか", "level": "L1" },
      { "tag": "muscular_body", "ja": "筋肉質", "level": "L1" },
      { "tag": "athletic_body", "ja": "アスリート体型", "level": "L1" },
      { "tag": "thicc", "ja": "極太もも・豊満", "level": "L2" },
      { "tag": "bubble_butt", "ja": "まんまる尻", "level": "L2" },
      { "tag": "wide_hips", "ja": "極端に広い腰回り", "level": "L2" },
      { "tag": "slim_thick", "ja": "上半身スリム＋下半身豊満", "level": "L2" },
      { "tag": "pear_shape", "ja": "下半身太り体型", "level": "L1" },
      { "tag": "apple_shape", "ja": "お腹ぽっこり体型", "level": "L1" },
      { "tag": "petite_body", "ja": "低身長スレンダー", "level": "L1" },
      { "tag": "tall_body", "ja": "高身長モデル体型", "level": "L1" },
      { "tag": "giantess_body", "ja": "巨人娘体型", "level": "L3" },
      { "tag": "hourglass", "ja": "砂時計体型", "level": "L1" },
      { "tag": "hourglass_exaggerated", "ja": "極端な砂時計体型", "level": "L2" },
      { "tag": "doll_like_body", "ja": "人形のような体型", "level": "L1" },
      { "tag": "pubic_hair_none", "ja": "パイパン/剃毛", "level": "L2" },
      { "tag": "pubic_hair_light", "ja": "うっすら陰毛", "level": "L1" },
      { "tag": "pubic_hair_trimmed", "ja": "整えられた陰毛", "level": "L2" },
      { "tag": "pubic_hair_full", "ja": "フル陰毛/ナチュラル", "level": "L2" },
      { "tag": "pubic_hair_bushy", "ja": "濃い陰毛/ボーボー", "level": "L3" },
      { "tag": "pubic_hair_wild", "ja": "はみ出す陰毛", "level": "L3" },
      { "tag": "pubic_hair_landing_strip", "ja": "陰毛ランディングストリップ", "level": "L2" },
      { "tag": "pubic_hair_triangle", "ja": "逆三角形スタイル", "level": "L2" },
      { "tag": "pubic_hair_heart", "ja": "ハート型スタイル", "level": "L2" },
      { "tag": "armpit_hair_none", "ja": "ワキ毛なし", "level": "L1" },
      { "tag": "armpit_hair_natural","ja": "ワキ毛あり", "level": "L2" },
      { "tag": "leg_hair_light", "ja": "うっすら脚毛", "level": "L1" },
      { "tag": "leg_hair_visible", "ja": "脚毛はっきり", "level": "L2" },
      { "tag": "arm_hair_light", "ja": "うっすら腕毛", "level": "L1" }
    ],
  
    "nipple": [
      { "tag": "small_nipples", "ja": "小さい乳首", "level": "L1" },
      { "tag": "medium_nipples", "ja": "普通の乳首", "level": "L1" },
      { "tag": "large_nipples", "ja": "大きな乳首", "level": "L1" },
      { "tag": "long_nipples", "ja": "突き出た乳首", "level": "L1" },
      { "tag": "puffy_nipples", "ja": "ぷっくり乳首", "level": "L1" },
      { "tag": "inverted_nipples", "ja": "陥没乳首", "level": "L1" },
      { "tag": "small_areolae", "ja": "小さな乳輪", "level": "L1" },
      { "tag": "large_areolae", "ja": "大きな乳輪", "level": "L1" },
      { "tag": "pink_areolae", "ja": "ピンク乳輪", "level": "L1" },
      { "tag": "areola_pale", "ja": "淡色乳輪", "level": "L1" },
      { "tag": "areola_brown", "ja": "ブラウン乳輪", "level": "L1" },
      { "tag": "areola_dark", "ja": "濃色乳輪", "level": "L1" },
      { "tag": "erect_nipples", "ja": "勃起乳首", "level": "L2" },
      { "tag": "wet_nipples", "ja": "濡れた乳首", "level": "L2" },
      { "tag": "dripping_milk", "ja": "母乳滴る乳首", "level": "L2" },
      { "tag": "leaking_nipples", "ja": "母乳にじむ乳首", "level": "L2" },
      { "tag": "pierced_nipples", "ja": "乳首ピアス", "level": "L2" },
      { "tag": "nipple_chains", "ja": "乳首チェーン", "level": "L2" },
      { "tag": "weighted_clamps", "ja": "重り付き乳首クリップ", "level": "L3" },
      { "tag": "injured_nipples", "ja": "傷ついた乳首", "level": "L3" },
      { "tag": "bleeding_nipples", "ja": "出血乳首", "level": "L3" },
      { "tag": "twisted_nipples",       "ja": "ひねられ乳首",       "level": "L2" },
      { "tag": "vacuum_pump_nipples",   "ja": "ポンプで膨らんだ乳首", "level": "L3" }
    ],
   "action": [
      { "tag": "handholding",        "ja": "手をつなぐ",          "level": "L1" },
      { "tag": "linking_arms",       "ja": "腕を組む",            "level": "L1" },
      { "tag": "hugging",            "ja": "抱きしめる",          "level": "L1" },
      { "tag": "hugging_from_back",  "ja": "背後から抱擁",        "level": "L1" },
      { "tag": "forehead_kiss",      "ja": "おでこにキス",        "level": "L1" },
      { "tag": "cheek_kiss",         "ja": "頬にキス",            "level": "L1" },
      { "tag": "kissing",            "ja": "キス",                "level": "L1" },
      { "tag": "french_kiss",        "ja": "ディープキス",        "level": "L2" },
      { "tag": "saliva_kiss",        "ja": "唾液の糸が見えるキス","level": "L2" },
      { "tag": "neck_kiss",          "ja": "首にキス",            "level": "L2" },
      { "tag": "nape_kiss",          "ja": "うなじにキス",        "level": "L2" },
      { "tag": "ear_bite",           "ja": "耳を噛む",            "level": "L2" },
      { "tag": "whispering_closely", "ja": "耳元でささやく",      "level": "L1" },

      { "tag": "stroking_cheek",     "ja": "頬をなでる",          "level": "L1" },
      { "tag": "brushing_hair",      "ja": "髪をなでる",          "level": "L1" },
      { "tag": "lifting_chin",       "ja": "顎を持ち上げる",      "level": "L1" },
      { "tag": "cupping_face",       "ja": "両手で頬を包む",      "level": "L1" },
      { "tag": "headpat",            "ja": "頭をなでる（頭ぽん）","level": "L1" },
      { "tag": "arm_around_shoulder","ja": "肩を抱く",            "level": "L1" },
      { "tag": "arm_around_waist",   "ja": "腰に手を回す",        "level": "L1" },
      { "tag": "pressing_chest",     "ja": "胸を押し付ける",      "level": "L2" },

      { "tag": "lap_pillow",         "ja": "膝枕",                "level": "L1" },
      { "tag": "bridal_carry",       "ja": "お姫様抱っこ",        "level": "L1" },
      { "tag": "dancing_close",      "ja": "密着して踊る",        "level": "L1" },

      { "tag": "smelling_hair",      "ja": "髪の匂いを嗅ぐ",      "level": "L1" },
      { "tag": "smelling_body",      "ja": "体の匂いを嗅ぐ",      "level": "L2" },
      { "tag": "smelling_underwear", "ja": "下着の匂いを嗅ぐ",    "level": "L2" },
      { "tag": "smelling_armpit",    "ja": "脇の匂いを嗅ぐ",      "level": "L2" },
      { "tag": "smelling_feet",      "ja": "足の匂いを嗅ぐ",      "level": "L2" },
      { "tag": "smelling_genitals",  "ja": "性器の匂いを嗅ぐ",    "level": "L3" },

      { "tag": "belly_kiss",         "ja": "お腹にキス",          "level": "L1" },
      { "tag": "navel_play",         "ja": "へそ責め",            "level": "L2" },
      { "tag": "thigh_kiss",         "ja": "太ももにキス",        "level": "L1" },
      { "tag": "inner_thigh_kiss",   "ja": "太ももの内側にキス",  "level": "L2" },
      { "tag": "leg_worship",        "ja": "脚フェチ（脚を愛でる）","level": "L2" },

      { "tag": "finger_licking",     "ja": "指を舐める",          "level": "L1" },
      { "tag": "licking",            "ja": "舐める（全般）",      "level": "L2" },
      { "tag": "sucking",            "ja": "吸う（指/耳/首/乳首）","level": "L2" },
      { "tag": "ear_teasing",        "ja": "耳を甘噛み/舐める",   "level": "L2" },
      { "tag": "neck_sucking",       "ja": "首筋を吸う（キスマーク）","level": "L2" },
      { "tag": "licking_sweat",      "ja": "汗を舐める",          "level": "L2" },

      { "tag": "nipple_teasing",     "ja": "乳首いじり",          "level": "L2" },
      { "tag": "nipple_sucking",     "ja": "乳首を吸う",          "level": "L2" },
      { "tag": "nipple_biting",      "ja": "乳首を噛む",          "level": "L2" },

      { "tag": "butt_squeezing",     "ja": "お尻を揉む",          "level": "L2" },
      { "tag": "thigh_fondling",     "ja": "太ももを触る",        "level": "L2" },
      { "tag": "crotch_rubbing",     "ja": "股間を触る/擦る",     "level": "L2" },
      { "tag": "hand_in_shirt",      "ja": "服の中に手を入れる",  "level": "L2" },
      { "tag": "hand_in_pants",      "ja": "パンツの中に手を入れる","level": "L2" },
      { "tag": "shirt_lift",         "ja": "服をめくる",          "level": "L2" },
      { "tag": "skirt_lift",         "ja": "スカートをめくる",    "level": "L2" },
      { "tag": "panties_pull_aside", "ja": "下着をずらす",        "level": "L2" },
      { "tag": "undressing",         "ja": "脱ぎかけ",            "level": "L1" },
      { "tag": "covered_nudity",     "ja": "手や物で隠す",        "level": "L1" },

      { "tag": "stroking_self",      "ja": "セルフ愛撫",          "level": "L2" },
      { "tag": "female_masturbation","ja": "女性オナニー",        "level": "L2" },
      { "tag": "male_masturbation",  "ja": "男性オナニー",        "level": "L2" },
      { "tag": "mutual_masturbation","ja": "相互オナニー",        "level": "L2" },
      { "tag": "toying",             "ja": "オナニーグッズ使用",  "level": "L3" },
      { "tag": "vibrator_use",       "ja": "バイブ使用",          "level": "L3" },
      { "tag": "dildo_use",          "ja": "ディルド使用",        "level": "L3" },
      { "tag": "butt_plug_use",      "ja": "アナルプラグ使用",    "level": "L3" },
      { "tag": "public_masturbation","ja": "人前オナニー",        "level": "L3" },

      { "tag": "fellatio",           "ja": "フェラチオ",          "level": "L3" },
      { "tag": "deepthroat",         "ja": "ディープスロート",    "level": "L3" },
      { "tag": "cunnilingus",        "ja": "クンニリングス",      "level": "L3" },
      { "tag": "rimming",            "ja": "アニリングス",        "level": "L3" },
      { "tag": "handjob",            "ja": "手コキ",              "level": "L3" },
      { "tag": "titjob",             "ja": "パイズリ",            "level": "L3" },
      { "tag": "footjob",            "ja": "足コキ",              "level": "L3" },
      { "tag": "self_spread",        "ja": "セルフくぱぁ（自分で開く）", "level": "L2" },

      { "tag": "penetration_vaginal","ja": "膣挿入",              "level": "L3" },
      { "tag": "penetration_anal",   "ja": "アナル挿入",          "level": "L3" },
      { "tag": "double_penetration", "ja": "二穴挿入",            "level": "L3" },
      { "tag": "pegging",            "ja": "ペニバン挿入",        "level": "L3" },
      { "tag": "fisting",            "ja": "フィスト",            "level": "L3" },

      { "tag": "urination",          "ja": "放尿",                "level": "L2" },
      { "tag": "wetting_clothes",    "ja": "お漏らし（服の中で）","level": "L2" },
      { "tag": "pee_stream",         "ja": "尿を出す瞬間",        "level": "L2" },
      { "tag": "pee_puddle",         "ja": "尿だまり",            "level": "L2" },
      { "tag": "pee_dripping",       "ja": "尿だらだら",          "level": "L2" },

      { "tag": "scat",               "ja": "排便/スカトロ",       "level": "L3" },
      { "tag": "scat_play",          "ja": "スカトロプレイ",      "level": "L3" },
      { "tag": "coprophagia",        "ja": "スカトロ食",          "level": "L3" },

      { "tag": "pull_aside_insertion_vaginal", "ja": "ずらし挿入（膣・下着/衣服をずらす）", "level": "L2" },
      { "tag": "pull_aside_insertion_anal",    "ja": "ずらし挿入（アナル・下着/衣服をずらす）", "level": "L3" },
      { "tag": "panties_aside_rubbing",        "ja": "パンツずらし愛撫（外側/素股）", "level": "L2" },
      { "tag": "zip_access_insertion",         "ja": "ジッパー開けての挿入", "level": "L2" },
      { "tag": "through_open_crotch_insertion","ja": "股あき衣装からの挿入", "level": "L2" },
      { "tag": "one_leg_in_panties_sex",       "ja": "片脚だけパンツ履いたままの挿入", "level": "L2" },

      { "tag": "fingering_vaginal",    "ja": "指入れ（膣）", "level": "L2" },
      { "tag": "fingering_anal",       "ja": "指入れ（アナル）", "level": "L3" },
      { "tag": "clit_rubbing",         "ja": "クリ愛撫（擦る/押す）", "level": "L2" },
      { "tag": "outercourse",          "ja": "素股（外性器擦り合わせ）", "level": "L2" },
      { "tag": "dry_humping",          "ja": "服の上から擦り付け", "level": "L1" },
      { "tag": "glans_teasing",        "ja": "亀頭いじり", "level": "L2" },
     
      { "tag": "just_the_tip",         "ja": "半挿し/先っぽだけ", "level": "L2" },
      { "tag": "deep_insert",          "ja": "奥まで挿入（根本まで）", "level": "L3" },
      { "tag": "grinding_crotch",      "ja": "股間擦り付け（挿入前の挑発）", "level": "L1" },
     
      { "tag": "condom_roll_on",       "ja": "コンドーム装着（手で装着）", "level": "L1" },
      { "tag": "condom_roll_on_mouth", "ja": "コンドームを口で装着", "level": "L2" },
      { "tag": "apply_lubricant",      "ja": "ローション/潤滑剤を塗る", "level": "L1" },
      { "tag": "handjob_gesture", "ja": "手コキポーズ（ジェスチャー）", "level": "L2" },
      { "tag": "fellatio_gesture", "ja": "フェラチオポーズ（ジェスチャー）", "level": "L2" },
      { "tag": "girl_trembling_with_sexual_climax", "ja": "絶頂で震える体", "level": "L2" },
      { "tag": "breast_squeeze",    "ja": "乳搾り（セルフ）",   "level": "L2" },
      { "tag": "breast_grab",       "ja": "乳掴み（正面/他人）","level": "L2" },
      { "tag": "breast_grab_back",  "ja": "乳掴み（背後から）", "level": "L2" },
      { "tag": "breast_milk",       "ja": "母乳（垂れる）",     "level": "L2" },
      { "tag": "nipple_to_nipple",  "ja": "乳首合わせ",          "level": "L2" }

    ],
    "action2": [
      { "tag": "creampie",           "ja": "中出し",              "level": "L3" },
      { "tag": "creampie_mark",      "ja": "中出し痕",            "level": "L2" },
      { "tag": "cum_inside",         "ja": "膣内射精",            "level": "L3" },
      { "tag": "cum_in_mouth",       "ja": "口内射精",            "level": "L3" },
      { "tag": "cum_swallow",        "ja": "精液飲み込み",        "level": "L3" },
      { "tag": "cum_spit",           "ja": "精液を吐き出す",      "level": "L2" },
      { "tag": "facial",             "ja": "顔射",                "level": "L2" },
      { "tag": "facial_after",       "ja": "顔射後",              "level": "L2" },
      { "tag": "cum_on_body",        "ja": "体に射精",            "level": "L2" },
      { "tag": "cum_on_breasts",     "ja": "胸射",                "level": "L2" },
      { "tag": "cum_on_ass",         "ja": "尻射",                "level": "L2" },
      { "tag": "cum_on_feet",        "ja": "足射",                "level": "L2" },
      { "tag": "cum_in_hair",        "ja": "髪に射精",            "level": "L2" },
      { "tag": "bukkake",            "ja": "ぶっかけ",            "level": "L3" },
      { "tag": "gangbang_cum",       "ja": "乱交射精",            "level": "L3" },
      { "tag": "multiple_creampie",  "ja": "連続中出し",          "level": "L3" },
      { "tag": "cum_overflow",       "ja": "精液溢れ",            "level": "L3" },
      { "tag": "cum_dripping",       "ja": "精液垂れ",            "level": "L2" },
      { "tag": "cum_pool",           "ja": "精液溜まり",          "level": "L3" },
      { "tag": "excessive_cum",      "ja": "大量射精",            "level": "L3" },

      { "tag": "squirting",          "ja": "潮吹き",              "level": "L2" },
      { "tag": "female_ejaculation", "ja": "女性の射精",          "level": "L2" },
      { "tag": "multiple_orgasm",    "ja": "連続絶頂",            "level": "L2" },
      { "tag": "simultaneous_orgasm","ja": "同時絶頂",            "level": "L2" },

      { "tag": "xray_cross_section",         "ja": "断面図（X線透過）",             "level": "L2" },
      { "tag": "xray_penetration_vaginal",   "ja": "断面図：膣挿入",                 "level": "L3" },
      { "tag": "xray_penetration_anal",      "ja": "断面図：肛門挿入",               "level": "L3" },
      { "tag": "xray_ejaculation_inside",    "ja": "断面図：膣内射精描写",           "level": "L3" },

      { "tag": "genital_join_closeup",       "ja": "結合部アップ",                   "level": "L3" },
      { "tag": "insertion_closeup_start",    "ja": "挿入直前アップ",                 "level": "L2" },
      { "tag": "insertion_closeup_mid",      "ja": "挿入中アップ",                   "level": "L3" },
      { "tag": "withdrawal_closeup",         "ja": "抜き差しアップ",                 "level": "L3" },
      { "tag": "pull_aside_insertion_closeup", "ja": "ずらし挿入・結合部アップ", "level": "L3" },
      { "tag": "just_the_tip_closeup",         "ja": "半挿しアップ", "level": "L3" },

      { "tag": "fluids_vaginal",             "ja": "愛液の描写（糸/滴）",            "level": "L2" },
      { "tag": "fluids_cum_drip",            "ja": "精液が垂れる描写",               "level": "L2" },
      { "tag": "fluids_mix_closeup",         "ja": "体液が混ざる結合部アップ",       "level": "L3" },

      { "tag": "condom_on",                  "ja": "コンドーム装着",                 "level": "L2" },
      { "tag": "condom_full",                "ja": "コンドーム精液溜まり",           "level": "L2" },
      { "tag": "condom_removal",             "ja": "コンドーム外し",                 "level": "L2" },
      { "tag": "condom_break",               "ja": "コンドーム破損",                 "level": "L2" },

      { "tag": "censor_mosaic",              "ja": "モザイク処理",                   "level": "L1" },
      { "tag": "censor_bar",                 "ja": "黒帯/白抜きによる検閲",          "level": "L1" },
      { "tag": "soft_focus_censor",          "ja": "ソフトフォーカスでぼかす",       "level": "L1" },

      { "tag": "aftercare_cuddle",           "ja": "事後の抱擁（アフターケア）",     "level": "L1" },
      { "tag": "cleaning_up_wipe",           "ja": "拭き取り/片付け描写",            "level": "L1" },
      { "tag": "towel_cover",                "ja": "タオルで隠す",                   "level": "L1" },
      { "tag": "sheets_stain_focus",         "ja": "シーツの染みを強調",             "level": "L2" },
      { "tag": "condom_insertion_vaginal", "ja": "コンドーム付き膣挿入", "level": "L2" },
      { "tag": "condom_insertion_anal",    "ja": "コンドーム付きアナル挿入", "level": "L2" },
      { "tag": "condom_creampie",          "ja": "コンドーム中出し", "level": "L2" },
      { "tag": "condom_withdrawal",        "ja": "コンドーム付き抜き差し", "level": "L2" },
      { "tag": "condom_visible",           "ja": "コンドームが見える描写", "level": "L1" },
      
      { "tag": "cum_on_hand",              "ja": "手に射精", "level": "L2" },
      { "tag": "cum_on_stomach",           "ja": "お腹に射精", "level": "L2" },
      { "tag": "cum_between_breasts",      "ja": "谷間射精", "level": "L2" },
      { "tag": "cum_clothes_stain",        "ja": "服に精液染み", "level": "L2" },
      
      { "tag": "post_cum_drip",            "ja": "射精後の精液滴り", "level": "L2" },
      { "tag": "post_squirting",           "ja": "絶頂後の潮吹き余韻", "level": "L2" }

    ],
        "participants": [
      { "tag": "solo",              "ja": "1人（単独）", "level": "L1" },
      { "tag": "1girl",             "ja": "女性1人", "level": "L1" },
      { "tag": "1boy",              "ja": "男性1人", "level": "L1" },
      
      { "tag": "2people",           "ja": "2人", "level": "L1" },
      { "tag": "1girl_1boy",        "ja": "男女ペア", "level": "L1" },
      { "tag": "2girls",            "ja": "女性2人（百合）", "level": "L1" },
      { "tag": "2boys",             "ja": "男性2人（BL）", "level": "L2" },
      
      { "tag": "3people",           "ja": "3人", "level": "L2" },
      { "tag": "1girl_2boys",       "ja": "女性1人＋男性2人", "level": "L2" },
      { "tag": "2girls_1boy",       "ja": "女性2人＋男性1人", "level": "L2" },
      { "tag": "3girls",            "ja": "女性3人", "level": "L2" },
      { "tag": "3boys",             "ja": "男性3人", "level": "L2" },
      
      { "tag": "4people",           "ja": "4人", "level": "L2" },
      { "tag": "1girl_3boys",       "ja": "女性1人＋男性3人", "level": "L3" },
      { "tag": "3girls_1boy",       "ja": "女性3人＋男性1人", "level": "L2" },
      { "tag": "2girls_2boys",      "ja": "男女2人ずつ", "level": "L2" },
      { "tag": "4girls",            "ja": "女性4人", "level": "L2" },
      { "tag": "4boys",             "ja": "男性4人", "level": "L2" },
      
      { "tag": "5people",           "ja": "5人", "level": "L3" },
      { "tag": "1girl_4boys",       "ja": "女性1人＋男性4人", "level": "L3" },
      { "tag": "group_sex",         "ja": "グループセックス", "level": "L3" },
      { "tag": "gangbang",          "ja": "輪姦", "level": "L3" },
      { "tag": "reverse_gangbang",  "ja": "逆ハーレム", "level": "L3" },
      { "tag": "orgy",              "ja": "乱交パーティー", "level": "L3" },
      { "tag": "multiple_boys",     "ja": "複数男性", "level": "L2" },
      { "tag": "multiple_girls",    "ja": "複数女性", "level": "L2" },
      { "tag": "mixed_group",       "ja": "男女混合グループ", "level": "L2" },
      
      { "tag": "threesome_ffm",     "ja": "3Pスタイル：女女男", "level": "L2" },
      { "tag": "threesome_mmf",     "ja": "3Pスタイル：男男女", "level": "L3" },
      { "tag": "threesome_fff",     "ja": "3Pスタイル：女女女", "level": "L2" },
      { "tag": "threesome_mmm",     "ja": "3Pスタイル：男男男", "level": "L2" },
      
      { "tag": "audience",          "ja": "観衆・見物人", "level": "L2" },
      { "tag": "voyeur",            "ja": "のぞき見", "level": "L2" },
      { "tag": "exhibitionism",     "ja": "露出プレイ", "level": "L2" },
      { "tag": "public_sex",        "ja": "人前セックス", "level": "L3" },
      { "tag": "filming",           "ja": "撮影・録画", "level": "L2" },
      { "tag": "livestreaming",     "ja": "ライブ配信", "level": "L2" }
    ],
    // ===== NSFW追加推奨タグ =====

// 1. ★★★ 最優先：インタラクション（2人目キャラ用）★★★
"interaction_nsfw": [
  // L1: 軽いスキンシップ
  { "tag": "intimate_touching", "ja": "密着タッチ", "level": "L1" },
  { "tag": "sensual_massage", "ja": "官能的マッサージ", "level": "L1" },
  { "tag": "body_worship", "ja": "身体を愛でる", "level": "L1" },
  { "tag": "mutual_undressing", "ja": "お互いに脱がせ合う", "level": "L1" },
  { "tag": "shower_together", "ja": "一緒にシャワー", "level": "L1" },
  { "tag": "bed_cuddle", "ja": "ベッドで密着", "level": "L1" },
  
  // L2: セクシャルアクション
  { "tag": "mutual_masturbation", "ja": "相互オナニー", "level": "L2" },
  { "tag": "69_position", "ja": "69ポジション", "level": "L2" },
  { "tag": "tribbing", "ja": "貝合わせ", "level": "L2" },
  { "tag": "double_dildo", "ja": "ダブルディルド", "level": "L2" },
  { "tag": "strap_on_sex", "ja": "ペニバンプレイ", "level": "L2" },
  { "tag": "roleplay_sex", "ja": "ロールプレイセックス", "level": "L2" },
  
  // L3: ハードコア
  { "tag": "double_penetration_mmf", "ja": "男性2人による二穴攻め", "level": "L3" },
  { "tag": "gangbang_receiving", "ja": "輪姦される", "level": "L3" },
  { "tag": "bdsm_session", "ja": "BDSM調教", "level": "L3" },
  { "tag": "master_slave_play", "ja": "主従プレイ", "level": "L3" },
  { "tag": "forced_orgasm", "ja": "強制絶頂", "level": "L3" },
  { "tag": "public_humiliation", "ja": "公開羞恥", "level": "L3" }
],

// 2. 背景（NSFW特化）
"background_nsfw": [
  { "tag": "love_hotel", "ja": "ラブホテル", "level": "L1" },
  { "tag": "strip_club", "ja": "ストリップクラブ", "level": "L2" },
  { "tag": "brothel", "ja": "売春宿", "level": "L3" },
  { "tag": "dungeon_bdsm", "ja": "BDSM地下室", "level": "L3" },
  { "tag": "adult_theater", "ja": "アダルト劇場", "level": "L2" },
  { "tag": "massage_parlor", "ja": "マッサージパーラー", "level": "L2" },
  { "tag": "webcam_room", "ja": "配信部屋", "level": "L1" },
  { "tag": "adult_convention", "ja": "アダルトイベント会場", "level": "L2" },
  { "tag": "sex_shop", "ja": "アダルトショップ", "level": "L1" },
  { "tag": "glory_hole", "ja": "グローリーホール", "level": "L3" }
],

// 3. 感情・心理状態（NSFW特化）
"emotion_nsfw": [
  { "tag": "aroused_confused", "ja": "戸惑いながら興奮", "level": "L1" },
  { "tag": "reluctant_pleasure", "ja": "嫌がりながら感じる", "level": "L2" },
  { "tag": "shameful_arousal", "ja": "恥ずかしがりながら興奮", "level": "L1" },
  { "tag": "prideful_submission", "ja": "プライドを捨てて従う", "level": "L2" },
  { "tag": "addicted_pleasure", "ja": "快楽依存", "level": "L3" },
  { "tag": "mind_break", "ja": "精神崩壊", "level": "L3" },
  { "tag": "corruption_progress", "ja": "堕落進行中", "level": "L2" },
  { "tag": "virginity_loss", "ja": "初体験の痛み", "level": "L2" },
  { "tag": "trembling_climax",  "ja": "絶頂で震える",       "level": "L2" },
],

// 4. 時間・シチュエーション
"timing_nsfw": [
  { "tag": "first_time", "ja": "初体験", "level": "L1" },
  { "tag": "after_party", "ja": "パーティー後", "level": "L1" },
  { "tag": "drunk_sex", "ja": "酔った勢いで", "level": "L2" },
  { "tag": "morning_after", "ja": "翌朝", "level": "L1" },
  { "tag": "lunch_break", "ja": "昼休み", "level": "L2" },
  { "tag": "overtime_office", "ja": "残業中", "level": "L2" },
  { "tag": "festival_night", "ja": "祭りの夜", "level": "L1" },
  { "tag": "graduation_celebration", "ja": "卒業祝い", "level": "L1" },
  { "tag": "birthday_surprise", "ja": "誕生日サプライズ", "level": "L1" }
],

  "occupation_nsfw": [
    { "tag": "teacher_student", "ja": "先生と生徒", "level": "L2" },
    { "tag": "tutor_student", "ja": "家庭教師と生徒", "level": "L2" },
    { "tag": "boss_secretary", "ja": "上司と秘書", "level": "L1" },
    { "tag": "ceo_employee", "ja": "社長と部下", "level": "L2" },
    { "tag": "doctor_patient", "ja": "医師と患者", "level": "L2" },
    { "tag": "nurse_patient", "ja": "看護師と患者", "level": "L2" },
    { "tag": "trainer_athlete", "ja": "トレーナーと選手", "level": "L1" },
    { "tag": "coach_student", "ja": "コーチと教え子", "level": "L1" },
    { "tag": "photographer_model", "ja": "カメラマンとモデル", "level": "L1" },
    { "tag": "idol_manager", "ja": "アイドルとマネージャー", "level": "L1" },
    { "tag": "landlord_tenant", "ja": "大家と住人", "level": "L2" },
    { "tag": "delivery_customer", "ja": "配達員と客", "level": "L2" },
    { "tag": "waiter_customer", "ja": "店員と客", "level": "L1" },
    { "tag": "police_citizen", "ja": "警官と市民", "level": "L2" },
    { "tag": "prison_guard_prisoner", "ja": "看守と囚人", "level": "L3" },
    { "tag": "soldier_commander", "ja": "兵士と指揮官", "level": "L2" },
    { "tag": "nun_priest", "ja": "シスターと神父", "level": "L3" },
    { "tag": "demon_summoner", "ja": "悪魔と召喚士", "level": "L3" },
  
    { "tag": "futanari_relationship", "ja": "ふたなりと女性", "level": "L3" },
    { "tag": "monster_human", "ja": "モンスターと人間", "level": "L3" },
    { "tag": "beastgirl_master", "ja": "ケモ耳少女と主人", "level": "L2" },
    { "tag": "alien_human", "ja": "異星人と人間", "level": "L3" }
  ]

  }
};
